name: Publish

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Run all the tests
        run: ./gradlew :youtubeparser:test

      - name: Stop Gradle
        run: ./gradlew --stop